### ISSUE TITLE
About the requirement.txt and image size

### ISSUE THREAD

**Issue by xhan233** [chenhaoxing/HDNet#10]
Hi,
I'm very interested in your work, and I'm also very grateful for you sharing your code. While reproducing your code, I encountered two issues: 
1）it seems that there's no requirement.txt；
2）the input images can only be 512x512 or 256x256, is that correct?

**Comment by chenhaoxing** [comment]
Hi. I would like to answer your question as follows:
1) There is indeed no requirement.txt. in practice I almost always use the latest packages.
2) The size of the input image can be customized, you just need to modify the corresponding preprocessed part in the dataloader.
