### ISSUE TITLE
how to solve the harmonized video consistency

### ISSUE THREAD

**Issue by wasahaiah** [chenhaoxing/HDNet#15]
Given an image, the harmonized quality is better other methods. But for video, the consistency is poor, how to solve it?

**Comment by chenhaoxing** [comment]
Video consistency is a problem that all video models need to solve. We believe that networks should be designed separately for such tasks, taking into account timing information. You can refer to video harmonization https://github.com/bcmi/Video-Harmonization-Dataset-HYouTube.
