### ISSUE TITLE
requirements.txt在哪里呀

### ISSUE THREAD

**Issue by LauraABCD** [chenhaoxing/HDNet#17]
没有找到requirements.txt，是不是忘记放上去了呢？

**Comment by chenhaoxing** [comment]
您好，我已经更新在主页。感觉大部分配置都可以，我是follow的RainNet。

**Comment by LauraABCD** [comment]
感谢您的回答，现在已经可以安装了，但是我这里还是有一个小问题，您的requirements.txt中有一个包是collections，我的操作系统是windows的，在anaconda中安装这个包的时候遇到下面的报错：couldn't find a version that satisfied the requirement collections(from versions:none)，我查找了许多解决的办法都没能顺利解决，想咨询一下您这个问题是怎么解决的呢如果您之前在测试的时候也遇到的话？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月01日 09:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chenhaoxing/HDNet] requirements.txt在哪里呀 (Issue #17) |

您好，我已经更新在主页。感觉大部分配置都可以，我是follow的RainNet。

**Comment by chenhaoxing** [comment]
你可以安装更新版本的collections。这个环境很早了，其实用些新环境也是可以的。

**Comment by LauraABCD** [comment]
好的感谢您的回答！我再试试新的环境！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月01日 13:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chenhaoxing/HDNet] requirements.txt在哪里呀 (Issue #17) |

你可以安装更新版本的collections。这个环境很早了，其实用些新环境也是可以的。
