### ISSUE TITLE
代码有些问题

### ISSUE THREAD

**Issue by LauraABCD** [chenhaoxing/HDNet#19]
在preprocess_iharmony4.py中并没有把调整后的图像数据写入新创建的数据集iHarmony4Resized，而是直接在原数据集中修改。我之前运行这个py文件时一直都是iHarmony4Resized文件夹是空的，后来用断点调试发现了这个问题，建议作者对原代码修改一下

**Comment by chenhaoxing** [comment]
您好。我们发现直接用原图在训练时resize会比提前resize效果好。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: LauraABCD ***@***.***>
发送时间: Saturday, March 2, 2024 6:16:10 PM
收件人: chenhaoxing/HDNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [chenhaoxing/HDNet] 代码有些问题 (Issue #19)


在preprocess_iharmony4.py中并没有把调整后的图像数据写入新创建的数据集iHarmony4Resized，而是直接在原数据集中修改。我之前运行这个py文件时一直都是iHarmony4Resized文件夹是空的，后来用断点调试发现了这个问题，建议作者对原代码修改一下

―

**Comment by LauraABCD** [comment]
哦哦原来是这样，感谢回答！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月03日 09:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chenhaoxing/HDNet] 代码有些问题 (Issue #19) |

您好。我们发现直接用原图在训练时resize会比提前resize效果好。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: LauraABCD ***@***.***>
发送时间: Saturday, March 2, 2024 6:16:10 PM
收件人: chenhaoxing/HDNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [chenhaoxing/HDNet] 代码有些问题 (Issue #19)


在preprocess_iharmony4.py中并没有把调整后的图像数据写入新创建的数据集iHarmony4Resized，而是直接在原数据集中修改。我之前运行这个py文件时一直都是iHarmony4Resized文件夹是空的，后来用断点调试发现了这个问题，建议作者对原代码修改一下

―
