### ISSUE TITLE
different results from the paper in average MSE

### ISSUE THREAD

**Issue by walkerwjt** [chenhaoxing/HDNet#5]
Hi, I followed the steps in the documentation to complete the training and testing. 
The dataset which I used is iHarmony4, all images are resized to 256 * 256, but the quantitative results are inconsistent with your paper:
                |  average MSE  | average  PSNR
my result |    16.463          |    40.805
paper       |    23.42           |    38.58
This result confuses me. Is there anything I missed? Thanks a lot !

**Comment by chenhaoxing** [comment]
Hi, you are not the first person that found these higher results. I’ll check that in few days.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: walkerwjt ***@***.***>
发送时间: Monday, March 6, 2023 2:55:36 PM
收件人: chenhaoxing/HDNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [chenhaoxing/HDNet] different results from the paper in average MSE (Issue #5)


Hi, I followed the steps in the documentation to complete the training and testing.
The dataset which I used is iHarmony4, all images are resized to 256 * 256, but the quantitative results are inconsistent with your paper:
| average MSE | average PSNR
my result | 16.463 | 40.805
paper | 23.42 | 38.58
This result confuses me. Is there anything I missed? Thanks a lot !

―

**Comment by chenhaoxing** [comment]
And, if it is possible, you can contact with me in wechat. My wechat id is chx_nju.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: walkerwjt ***@***.***>
发送时间: Monday, March 6, 2023 2:55:36 PM
收件人: chenhaoxing/HDNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [chenhaoxing/HDNet] different results from the paper in average MSE (Issue #5)


Hi, I followed the steps in the documentation to complete the training and testing.
The dataset which I used is iHarmony4, all images are resized to 256 * 256, but the quantitative results are inconsistent with your paper:
| average MSE | average PSNR
my result | 16.463 | 40.805
paper | 23.42 | 38.58
This result confuses me. Is there anything I missed? Thanks a lot !

―

**Comment by chenhaoxing** [comment]
Hello. I have conducted multiple rounds of experiments. I found such a bias from the dataset. If the image is resized in advance, then the result will become worse. On the contrary, if the images are resized at the time of training, the results obtained are better. This may be due to the fact that resizing in advance affects the image quality. We will update the results of our paper after the complete experiment.

**Comment by walkerwjt** [comment]
Sorry for the late reply! 
OK, thank you very much! In this case, the performance of HDNet is much better than other papers! !
Recently, I am doing online augmentation experiments on brightness and saturation, and it seems to be a good trick!

**Comment by chenhaoxing** [comment]
Thanks for your sharing.
