### ISSUE TITLE
 New Code?

### ISSUE THREAD

**Issue by Michael-H777** [chenhaoxing/HDNet#6]
Hello dear developers, 

any update on the new code? 

Thanks

**Comment by chenhaoxing** [comment]
Hi, we will release our new code in 5 days.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Michael-H777 ***@***.***>
发送时间: Sunday, April 30, 2023 4:41:44 AM
收件人: chenhaoxing/HDNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [chenhaoxing/HDNet] New Code? (Issue #6)


Hello dear developers,

any update on the new code?

Thanks

―

**Comment by sanchit88** [comment]
Can you please update the repo. with the new code and model? Thanks!

**Comment by chenhaoxing** [comment]
> Can you please update the repo. with the new code and model? Thanks!

Hi, we have uploaded our code. You can use it now.
