### ISSUE TITLE
request IHD_train.txt and IHD_test.txt

### ISSUE THREAD

**Issue by dorianzhang7** [chenhaoxing/HDNet#7]
Hi author, I'm trying your harmonization method. But when I was processing the data set, I did not find IHD_train.txt and IHD_test.txt. During the training process, the data set could not be preprocessed and an error was reported.
Could you please upload the two files?
Thank you very much for your reply

**Comment by chenhaoxing** [comment]
Hi, here are files you need.

[IHD_test.txt](https://github.com/chenhaoxing/HDNet/files/11539246/IHD_test.txt)
[IHD_train.txt](https://github.com/chenhaoxing/HDNet/files/11539249/IHD_train.txt)
