### ISSUE TITLE
Exception when calling struct similarity

### ISSUE THREAD

**Issue by darshats** [chenhaoxing/HDNet#9]
Hi,
I find that when computing struct similarity in evaluation, unless channel_axis is set, there is an exception. Its a small fix, but I wonder if I'm doing something wrong otherwise everyone will get this error for RGB images. 
Thanks!

**Comment by lexilii** [comment]
I got the same error
"in structural_similarity raise ValueError(ValueError: win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the function call, with an odd value less than or equal to the smaller side of your images. If your images are multichannel (with color channels), set channel_axis to the axis number corresponding to the channels."

**Comment by chenhaoxing** [comment]
Sorry for replying only now, you just need to modify the code as below to work properly.
```python
ssim_score = ssim(util.tensor2im(pred), util.tensor2im(gt), data_range=255, channel_axis=-1
```
